IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
EXEC [Trustify].[dbo].[sp_fulltext_database] @action = 'enable';
END
ALTER DATABASE [Trustify] SET ANSI_NULL_DEFAULT OFF; 
ALTER DATABASE [Trustify] SET ANSI_NULLS OFF; 
ALTER DATABASE [Trustify] SET ANSI_PADDING OFF; 
ALTER DATABASE [Trustify] SET ANSI_WARNINGS OFF; 
ALTER DATABASE [Trustify] SET ARITHABORT OFF; 
ALTER DATABASE [Trustify] SET AUTO_CLOSE OFF; 
ALTER DATABASE [Trustify] SET AUTO_SHRINK OFF; 
ALTER DATABASE [Trustify] SET AUTO_UPDATE_STATISTICS ON; 
ALTER DATABASE [Trustify] SET CURSOR_CLOSE_ON_COMMIT OFF; 
ALTER DATABASE [Trustify] SET CURSOR_DEFAULT  GLOBAL; 
ALTER DATABASE [Trustify] SET CONCAT_NULL_YIELDS_NULL OFF; 
ALTER DATABASE [Trustify] SET NUMERIC_ROUNDABORT OFF; 
ALTER DATABASE [Trustify] SET QUOTED_IDENTIFIER OFF; 
ALTER DATABASE [Trustify] SET RECURSIVE_TRIGGERS OFF; 
ALTER DATABASE [Trustify] SET  DISABLE_BROKER WITH ROLLBACK IMMEDIATE; 
ALTER DATABASE [Trustify] SET AUTO_UPDATE_STATISTICS_ASYNC OFF; 
ALTER DATABASE [Trustify] SET DATE_CORRELATION_OPTIMIZATION OFF; 
ALTER DATABASE [Trustify] SET TRUSTWORTHY OFF ;
ALTER DATABASE [Trustify] SET ALLOW_SNAPSHOT_ISOLATION OFF; 
ALTER DATABASE [Trustify] SET PARAMETERIZATION SIMPLE; 
ALTER DATABASE [Trustify] SET READ_COMMITTED_SNAPSHOT OFF; 
ALTER DATABASE [Trustify] SET HONOR_BROKER_PRIORITY OFF; 
ALTER DATABASE [Trustify] SET RECOVERY FULL; 
ALTER DATABASE [Trustify] SET  MULTI_USER; 
ALTER DATABASE [Trustify] SET PAGE_VERIFY CHECKSUM;  
ALTER DATABASE [Trustify] SET DB_CHAINING OFF; 
ALTER DATABASE [Trustify] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ); 
ALTER DATABASE [Trustify] SET TARGET_RECOVERY_TIME = 60 SECONDS; 
ALTER DATABASE [Trustify] SET DELAYED_DURABILITY = DISABLED; 
EXEC sys.sp_db_vardecimal_storage_format N'Trustify', N'ON';
ALTER DATABASE [Trustify] SET QUERY_STORE = OFF
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
EXEC [Trustify].[dbo].[sp_fulltext_database] @action = 'enable';
END
ALTER DATABASE [Trustify] SET ANSI_NULL_DEFAULT OFF; 
ALTER DATABASE [Trustify] SET ANSI_NULLS OFF; 
ALTER DATABASE [Trustify] SET ANSI_PADDING OFF; 
ALTER DATABASE [Trustify] SET ANSI_WARNINGS OFF; 
ALTER DATABASE [Trustify] SET ARITHABORT OFF; 
ALTER DATABASE [Trustify] SET AUTO_CLOSE OFF; 
ALTER DATABASE [Trustify] SET AUTO_SHRINK OFF; 
ALTER DATABASE [Trustify] SET AUTO_UPDATE_STATISTICS ON; 
ALTER DATABASE [Trustify] SET CURSOR_CLOSE_ON_COMMIT OFF; 
ALTER DATABASE [Trustify] SET CURSOR_DEFAULT  GLOBAL; 
ALTER DATABASE [Trustify] SET CONCAT_NULL_YIELDS_NULL OFF; 
ALTER DATABASE [Trustify] SET NUMERIC_ROUNDABORT OFF; 
ALTER DATABASE [Trustify] SET QUOTED_IDENTIFIER OFF; 
ALTER DATABASE [Trustify] SET RECURSIVE_TRIGGERS OFF; 
ALTER DATABASE [Trustify] SET  DISABLE_BROKER; 
ALTER DATABASE [Trustify] SET AUTO_UPDATE_STATISTICS_ASYNC OFF; 
ALTER DATABASE [Trustify] SET DATE_CORRELATION_OPTIMIZATION OFF; 
ALTER DATABASE [Trustify] SET TRUSTWORTHY OFF; 
ALTER DATABASE [Trustify] SET ALLOW_SNAPSHOT_ISOLATION OFF; 
ALTER DATABASE [Trustify] SET PARAMETERIZATION SIMPLE; 
ALTER DATABASE [Trustify] SET READ_COMMITTED_SNAPSHOT OFF; 
ALTER DATABASE [Trustify] SET HONOR_BROKER_PRIORITY OFF; 
ALTER DATABASE [Trustify] SET RECOVERY FULL; 
ALTER DATABASE [Trustify] SET  MULTI_USER; 
ALTER DATABASE [Trustify] SET PAGE_VERIFY CHECKSUM;  
ALTER DATABASE [Trustify] SET DB_CHAINING OFF; 
ALTER DATABASE [Trustify] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ); 
ALTER DATABASE [Trustify] SET TARGET_RECOVERY_TIME = 60 SECONDS; 
ALTER DATABASE [Trustify] SET DELAYED_DURABILITY = DISABLED; 
EXEC sys.sp_db_vardecimal_storage_format N'Trustify', N'ON';
ALTER DATABASE [Trustify] SET QUERY_STORE = OFF;